import {
  ChartColumnIncreasing,
  ClipboardCheck,
  CreditCard,
  CarFront,
  Gauge,
  Layers3,
  Package,
  ReceiptText,
  Settings,
  ShieldUser,
  ShoppingBag,
  Sparkles,
  Users,
  UserRound,
} from 'lucide-react'

export type NavAudience = 'all' | 'admin' | 'manager' | 'operator' | 'seller'

export const navigationItems = [
  {
    path: '/dashboard',
    label: 'Dashboard',
    description: 'Resumen general y actividad',
    icon: Gauge,
    audience: 'manager' as const,
    section: 'general' as const,
  },
  {
    path: '/my-space',
    label: 'Mi espacio',
    description: 'Stock, cortes y saldos personales',
    icon: UserRound,
    audience: 'all' as const,
    section: 'general' as const,
  },
  {
    path: '/my-earnings',
    label: 'Mis ganancias',
    description: 'Comisión y progreso de tus X',
    icon: Sparkles,
    audience: 'seller' as const,
    section: 'general' as const,
  },
  {
    path: '/employees',
    label: 'Empleados',
    description: 'Equipo, perfiles e historial',
    icon: Users,
    audience: 'admin' as const,
    section: 'admin' as const,
  },
  {
    path: '/products',
    label: 'Productos',
    description: 'Catálogo, costos y stock',
    icon: Package,
    audience: 'admin' as const,
    section: 'admin' as const,
  },
  {
    path: '/inventory',
    label: 'Inventario',
    description: 'Entradas, salidas y ajustes',
    icon: Layers3,
    audience: 'manager' as const,
    section: 'admin' as const,
  },
  {
    path: '/vehicles',
    label: 'Vehículos',
    description: 'Flotilla, asignación y mantenimiento',
    icon: CarFront,
    audience: 'admin' as const,
    section: 'admin' as const,
  },
  {
    path: '/sales',
    label: 'Ventas',
    description: 'Registro y rendimiento',
    icon: ShoppingBag,
    audience: 'operator' as const,
    section: 'operacion' as const,
  },
  {
    path: '/cuts',
    label: 'Cortes',
    description: 'Cierres y comisiones',
    icon: ClipboardCheck,
    audience: 'manager' as const,
    section: 'operacion' as const,
  },
  {
    path: '/finance',
    label: 'Deudas / Ahorros',
    description: 'Movimientos y saldos',
    icon: CreditCard,
    audience: 'manager' as const,
    section: 'operacion' as const,
  },
  {
    path: '/payments',
    label: 'Pagos',
    description: 'Salarios, bonos y comisiones',
    icon: ReceiptText,
    audience: 'manager' as const,
    section: 'operacion' as const,
  },
  {
    path: '/reports',
    label: 'Reportes',
    description: 'Métricas y exportaciones',
    icon: ChartColumnIncreasing,
    audience: 'admin' as const,
    section: 'admin' as const,
  },
  {
    path: '/settings',
    label: 'Configuración',
    description: 'Preferencias y seguridad',
    icon: Settings,
    audience: 'admin' as const,
    section: 'admin' as const,
  },
  {
    path: '/admin',
    label: 'Centro admin',
    description: 'Acciones del patron y re-stock',
    icon: ShieldUser,
    audience: 'admin' as const,
    section: 'admin' as const,
  },
] as const

export const routeTitles: Record<string, string> = {
  '/dashboard': 'Dashboard',
  '/my-space': 'Mi espacio',
  '/my-earnings': 'Mis ganancias',
  '/admin': 'Centro admin',
  '/employees': 'Empleados',
  '/products': 'Productos',
  '/inventory': 'Inventario',
  '/vehicles': 'Vehículos',
  '/sales': 'Ventas',
  '/cuts': 'Cortes',
  '/finance': 'Deudas y ahorros',
  '/payments': 'Pagos',
  '/reports': 'Reportes',
  '/settings': 'Configuración',
  '/login': 'Acceso',
}
